apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: kube-system
  name: faisaldns-eastus-cloudapp-azure-com-cert-staging
spec:
  secretName: faisaldns-eastus-cloudapp-azure-com-staging
  dnsNames:
  - faisaldns.eastus.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - faisaldns.eastus.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer  